source_directory: "/path/to/source_directory"
destination_directory: "/path/to/destination_directory"
small_thumbnail_dimension: [80, 80]
medium_thumbnail_dimension: [300, 300]
large_thumbnail_dimension: [500, 500]
